apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Chart.AppVersion }}
spec:
  replicas: {{ .Values.replicaCount}}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - env:
        - name: TZ
          value: {{ quote .Values.container.env.tz }}
        - name: PUID
          value: {{ quote .Values.container.env.puid }}
        - name: PGID
          value: {{ quote .Values.container.env.pgid }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: radarr
        ports:
        - containerPort: 7878
          name: radarr
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: vol-radarr-config
        - mountPath: /mnt/media
          name: vol-radarr-media
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: vol-radarr-config
        persistentVolumeClaim:
          claimName: pvc-radarr-config
      - name: vol-radarr-media
        nfs:
          path: /volume1/plex
          server: 10.0.0.66
      
        
        
