apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Chart.AppVersion }}
spec:
  replicas: {{ .Values.replicaCount}}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: "pvc-{{ .Chart.Name }}-config"
        - name: "vol-{{ .Chart.Name }}-media"
          nfs:
            path: "{{ .Values.container.volumes.media.mediaServerPath }}"
            server: "{{ .Values.container.volumes.media.mediaServerIP }}"
      containers:
      - env:
        - name: TZ
          value: {{ quote .Values.container.env.tz }}
        - name: PUID
          value: {{ quote .Values.container.env.puid }}
        - name: PGID
          value: {{ quote .Values.container.env.pgid }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: radarr
        ports:
        - containerPort: 7878
          name: radarr
          protocol: TCP
        resources: {}
        volumeMounts:
          - mountPath: {{ .Values.container.volumes.config.path }}
            name: "vol-{{ .Chart.Name }}-config"
          - mountPath: {{ .Values.container.volumes.media.path }}
            name: "vol-{{ .Chart.Name }}-media"
      
        
        
