apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Chart.AppVersion }}
spec:
  replicas: {{ .Values.replicaCount}}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      volumes:
        - name: "val-{{ .Chart.Name }}-config"
          persistentVolumeClaim:
            claimName: "pvc-{{ .Chart.Name }}-config"
        - name: "vol-{{ .Chart.Name }}-media"
          nfs:
            path: "{{ .Values.container.volumes.media.mediaServerPath }}"
            server: "{{ .Values.container.volumes.media.mediaServerIP }}"
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: TZ
            value: {{ .Values.container.env.TZ }}
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
        ports:
          - containerPort: 7878
            name: {{ .Values.service.targetPort }}
            protocol: TCP
        volumeMounts:
          - mountPath: {{ .Values.container.volumes.config.path }}
            name: "vol-{{ .Chart.Name }}-config"
          - mountPath: {{ .Values.container.volumes.media.path }}
            name: "vol-{{ .Chart.Name }}-media"
      
        
        
