---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: pvc-radarr-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
  requests:
    storage: {{ .Values.container.volumes.config.size | default "2Gi"}}
