---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "pvc-{{ .Chart.Name }}-config"
spec:
  volumeName: "vol-{{ .Chart.Name}}-config"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.container.volumes.config.size }}"
