---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .Chart.Name }}-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: { { .Values.container.volumes.config.size | default "2Gi" } }
