---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "vol-{{ .Chart.Name }}-config"
  namespace: { { .Release.Namespace } }
spec:
  capacity:
    storage: "{{ .Values.container.volumes.config.size }}"
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: delete
  storageClass: "{{ .Values.container.volumes.config.storageClass}}"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "vol-{{ .Chart.Name }}-media"
  namespace: { { .Release.Namespace } }
spec:
  nfs:
    path: { { .Values.container.volumes.media.mediaServerPath } }
    server: { { .Values.container.volumes.mediaServerIP } }
