---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "vol-{{ .Chart.Name }}-config"
  namespace: { { .Release.Namespace } }
spec:
  capacity:
    storage: "{{ .Values.container.volumes.config.size }}"
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: delete
  storageClass: "{{ .Values.container.volumes.config.storageClass}}"
