{{- if .Values.loadBalancer.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "jellyfin.fullname" . }} 
spec:
  selector:
    app: {{ include "jellyfin.fullname" . }}           
  ports:                      
  - port: 8096             
    targetPort: 8096       
    name: http             
    protocol: TCP
  - port: 8920
    targetPort: 8920
    name: https
  - port: 1900
    name: service-discovery
    targetPort: 1900
    protocol: UDP
  - port: 7359
    targetPort: 7359
    name: auto-discovery
    protocol: UDP
  type: LoadBalancer
  {{- if .Values.loadBalancer.IP }}
  loadBalancerIP: {{ .Values.loadBalancer.IP }}
  {{- end }}
{{- end }}