apiVersion: v2
name: tracearr
description: A Helm chart for running Tracearr on k8s
type: application
version: 0.1.3
appVersion: "latest"
dependencies:
  - name: common
    version: 0.5.6
    repository: "https://coltonhughes.github.io/helm-charts"
  - name: valkey
    version: "0.9.3"
    repository: "https://valkey.io/valkey-helm/"
    condition: tracearr.stateful.valkey.useDependency
