apiVersion: v2
name: tracearr
description: A Helm chart for running Tracearr on k8s
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: common
    version: 0.5.6
    repository: "https://coltonhughes.github.io/helm-charts"
