{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "jackett.fullname" . }}
  labels:
      {{- include "jackett.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
      requests:
          storage: {{ .Values.persistence.size | quote }}
{{- end }}