apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sabnzbd.fullname" . }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
  {{- if .Values.ingress.acme }}
    kubernetes.io/tls-acme: "true"
  {{- end }}
    kubernetes.io/ingress.class: {{ .Values.ingress.class | quote }}
  {{- if eq .Values.ingress.class "nginx" }}
    nginx.ingress.kubernetes.io/rewrite-target: /
  {{- end }}
  labels:
    name: {{ include "sabnzbd.fullname" . }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  tls:
    - hosts:
        - {{ .Values.ingress.fqdn }}
      secretName: "{{ include "sabnzbd.fullname" . }}-tls"
  rules:
    - host: {{ .Values.ingress.fqdn }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ include "sabnzbd.fullname" . }}
                port:
                  number: {{ .Values.service.port }}