apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qbittorrent.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "qbittorrent.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "qbittorrent.fullname" . }}
    spec:
      containers:
        - name: {{ include "qbittorrent.fullname" . }}  
          image: {{ .Values.qbittorrent.image.repository }}:{{ .Values.qbittorrent.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.qbittorrent.image.pullPolicy }}
          env:
            - name: TZ
              value: {{ quote .Values.qbittorrent.env.tz }}
            - name: PUID
              value: {{ quote .Values.qbittorrent.env.puid }}
            - name: PGID
              value: {{ quote .Values.qbittorrent.env.pgid }}
            - name: WEBUI_PORT
              value: "{{ .Values.service.port }}"
            - name: TORRENT_PORT
              value: "50000"
          ports:
            - containerPort: {{ .Values.service.port }}
              name: qbittorrent
              protocol: TCP
            - containerPort: 50000
              name: torrent
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: qbittorrent-config
          {{- if .Values.qbittorrent.additionalMounts }}
            {{- .Values.qbittorrent.additionalMounts | toYaml | nindent 12 }}
          {{- end }}
        - name: vpn
          image: {{ .Values.vpn.image.repository }}:{{ .Values.vpn.image.tag | default "latest" }}
          imagePullPolicy: {{ .Values.vpn.image.pullPolicy }}
          env:
            - name: VPN_SERVICE_PROVIDER
              value: custom
            - name: VPN_TYPE
              value: {{ quote .Values.vpn.env.type | default "wireguard" }}
            - name: WIREGUARD_ENDPOINT_IP
              value: {{ quote .Values.vpn.env.vpn_endpoint_ip }}
            - name: WIREGUARD_ENDPOINT_PORT
              value: {{ quote .Values.vpn.env.vpn_endpoint_port }}
            {{- if .Values.vpn.env.wg_existing_secret }}
            - name: WIREGUARD_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  key: WIREGUARD_PUBLIC_KEY
                  name: {{ .Values.vpn.env.wg_existing_secret }}
                  optional: false
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: WIREGUARD_PRIVATE_KEY
                  name: {{ .Values.vpn.env.wg_existing_secret }}
                  optional: false
            - name: WIREGUARD_PRESHARED_KEY
              valueFrom:
                secretKeyRef:
                  key: WIREGUARD_PRESHARED_KEY
                  name: {{ .Values.vpn.env.wg_existing_secret }}
                  optional: false
            {{- else }}
            - name: WIREGUARD_PUBLIC_KEY
              value: {{ .Values.vpn.env.wg_public_key }}
            - name: WIREGUARD_PRIVATE_KEY
              value: {{ .Values.vpn.env.wg_private_key }}
            - name: WIREGUARD_PRESHARED_KEY
              value: {{ .Values.vpn.env.wg_preshared_key }}
            {{- end }}
            - name: WIREGUARD_ADDRESSES
              value: {{ quote .Values.vpn.env.wireguard_cidr }}
            - name: FIREWALL_INPUT_PORTS
              value: "8080,50000"
            - name: FIREWALL_VPN_INPUT_PORTS
              value: '50000'
            - name: DOT
              value: "off"
            - name: DNS_ADDRESS
              value: {{ quote .Values.vpn.env.dns_address | default "8.8.8.8" }}
          ports:
            - containerPort: 8080
              name: vpn
              protocol: TCP
            - containerPort: 50000
              name: torrent
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
            privileged: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: qbittorrent-config
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "qbittorrent.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- if .Values.qbittorrent.additionalVolumes }}
        {{- .Values.qbittorrent.additionalVolumes | toYaml | nindent 8 }}
      {{- end }}