apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbittorrent.fullname" . | trunc 15 }}
spec:
  selector:
    app: {{ include "qbittorrent.fullname" . | trunc 15 }}
  type: LoadBalancer
  {{- if .Values.loadBalancer.IP }}
  loadBalancerIP: {{ .Values.loadBalancer.IP }}
  {{- end }}
  ports:
    - name: ui
      protocol: {{ .Values.service.protocol | default "TCP" }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
    - name: torrent
      protocol: TCP
      port: 50000
      targetPort: torrent