apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbittorrent.fullname" . }}
spec:
  selector:
    app: {{ include "qbittorrent.fullname" . }}
  type: LoadBalancer
  {{- if .Values.loadBalancer.IP }}
  loadBalancerIP: {{ .Values.loadBalancer.IP }}
  {{- end }}
  ports:
    - protocol: {{ .Values.service.protocol | default "TCP" }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}