apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gha-cache.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "gha-cache.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "gha-cache.fullname" . }}
    spec:
      volumes:
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "gha-cache.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- if .Values.persistence.additionalVolumes }}
        {{- .Values.persistence.additionalVolumes | toYaml | nindent 8 }}
      {{- end }}
      containers:
      - env:
        - name: URL_ACCESS_TOKEN
          value: {{ quote .Values.container.env.url_access_token | default "supersecrettoken" }}
        - name: BASE_URL
          value: {{ quote .Values.container.env.base_url }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ include "gha-cache.fullname" . }}
        ports:
        - containerPort: 7878
          name: {{ include "gha-cache.fullname" . }}
          protocol: TCP
        resources: {}
        volumeMounts:
          - mountPath: /data
            name: data