apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plex.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "plex.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "plex.fullname" . }}
    spec:
      {{- if .Values.gpu.enabled }}
      {{ if eq .Values.gpu.type "nvidia" }}
      runtimeClassName: nvidia
      {{ end}}
      {{- end }}
      volumes:
        - name: config
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "plex.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- if .Values.persistence.additionalVolumes }}
        {{- .Values.persistence.additionalVolumes | toYaml | nindent 8 }}
      {{- end }}
      containers:
      - env:
        - name: TZ
          value: {{ quote .Values.container.env.tz }}
        - name: PUID
          value: {{ quote .Values.container.env.puid }}
        - name: PGID
          value: {{ quote .Values.container.env.pgid }}
        - name: VERSION
          value: {{ quote .Values.container.env.version }}
        {{- if .Values.container.env.plexClaim }}
        - name: PLEX_CLAIM
          value: {{ quote .Values.container.env.plexClaim}}
        {{- end }}
        {{- if .Values.gpuEnabled }}
        - name: NVIDIA_VISIBLE_DEVICES 
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES  
          value: "compute,video,utility"
        {{- end }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ include "plex.fullname" . }}
        {{- if .Values.gpu.enabled }}
        resources:
          requests:
          {{- if eq .Values.gpu.type "nvidia" }}
            nvidia.com/gpu: 1
          {{ else if eq .Values.gpu.type "intel" }}
            gpu.intel.com/i915: "1"
          limits:
          {{- if eq .Values.gpu.type "nvidia" }}
            nvidia.com/gpu: 1
          {{ else if eq .Values.gpu.type "intel" }}
            gpu.intel.com/i915: "1"
          {{ end }}
        {{- end }}
        ports:
          - containerPort: 32400    
            name: {{ include "plex.fullname" . }}
            protocol: TCP
          - containerPort: 32469
            name: dlna-tcp
            protocol: TCP
          - containerPort: 1900
            name: dlna-udp
            protocol: UDP
          - containerPort: 3005
            name: plex-companion
            protocol: TCP  
          - containerPort: 5353
            name: discovery-udp
            protocol: UDP  
          - containerPort: 8324
            name: plex-roku
            protocol: TCP  
          - containerPort: 32410
            name: gdm-32410
            protocol: UDP
          - containerPort: 32412
            name: gdm-32412
            protocol: UDP
          - containerPort: 32413
            name: gdm-32413
            protocol: UDP
          - containerPort: 32414
            name: gdm-32414
            protocol: UDP
        volumeMounts:
          - mountPath: /config
            name: config
        {{- if .Values.persistence.additionalMounts }}
          {{- .Values.persistence.additionalMounts | toYaml | nindent 10 }}
        {{- end }}