{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tautulli.fullname" . }}
  labels:
    name: {{ include "tautulli.fullname" . }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
    - host: {{ .Values.ingress.fqdn }}
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /
            backend:
              service:
                name: {{ include "tautulli.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}