apiVersion: v1
kind: Service
metadata:
  name: {{ include "sonarr.fullname" . }}
spec:
  selector:
    app: {{ include "sonarr.fullname" . }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: {{ .Values.service.protocol | default "TCP" }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}