apiVersion: v2
name: unifi-mcp
description: UniFi Network Controller API MCP server exposed over streamable HTTP
type: application
version: 0.1.0
appVersion: "0.2.6"
dependencies:
  - name: common
    version: 0.5.8
    repository: "https://coltonhughes.github.io/helm-charts"
