{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "lazylibrarian.fullname" . }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    name: {{ include "lazylibrarian.fullname" . }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.fqdn }}
      secretName: "lazylibrarian-tls"
  ingressClassName: {{ .Values.ingress.class }}
  rules:
    - host: {{ .Values.ingress.fqdn }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ include "lazylibrarian.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}