apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "factorio.fullname" . }}-config
  labels:
      {{- include "factorio.labels" . | nindent 4 }}
data: 
    server-adminlist.json: |
{{ toJson .}}
{{- end -}}