{{- $downloads := .Values.downloadsPersistence -}}
{{- if and $downloads.enabled (not $downloads.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $downloads.claimName | default (printf "%s-downloads" (include "common.fullname" .)) }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $downloads.accessMode | quote }}
  {{- if $downloads.storageClass }}
  storageClassName: {{ $downloads.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ $downloads.size | quote }}
{{- end }}
