apiVersion: v2
name: seerr
description: A Helm chart for running Seerr on k8s
type: application
version: 0.1.0
appVersion: "3.0.1"
dependencies:
  - name: common
    version: 0.5.6
    repository: "https://coltonhughes.github.io/helm-charts"
