apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bambuddy
  namespace: bambuddy
spec:
  interval: 30m
  releaseName: bambuddy
  chart:
    spec:
      chart: bambuddy
      version: "0.1.1"
      sourceRef:
        kind: HelmRepository
        name: colton-helm-charts
        namespace: flux-system
      interval: 1h
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      tag: latest
    database:
      secret:
        enabled: true
        create: true
      cnpg:
        enabled: true
        createCredentialsSecret: false
        existingCredentialsSecret:
          enabled: true
          name: bambuddy-cnpg-credentials
        credentials:
          username: bambuddy
          database: bambuddy
    service:
      type: LoadBalancer
    virtualPrinter:
      service:
        exposeCorePorts: true
        exposePassivePortSlice: true
      passivePortSlicing:
        enabled: true
        startPort: 50000
        sliceCount: 3
        portsPerSlice: 10
    httpRoute:
      enabled: true
      parentRefs:
        - name: internal
          namespace: gateway
      hostnames:
        - bambuddy.example.com
