apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secuimage-backend.fullname" . }}
  labels:
    {{- include "secuimage-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "secuimage-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "secuimage-backend.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "{{ .Values.metrics.enabled }}"
        prometheus.io/port: "{{ .Values.metrics.port }}"
        prometheus.io/path: "{{ .Values.metrics.serviceMonitor.path }}"
    spec:
      serviceAccountName: {{ include "secuimage-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/docker/registry/config.yml
              subPath: config.yml
            - name: storage
              mountPath: /var/lib/registry
      volumes:
        - name: config
          configMap:
            name: {{ include "secuimage-backend.fullname" . }}
        - name: storage
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "secuimage-backend.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}