name: Renovate

env:
  LOG_LEVEL: info

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  renovate:
    runs-on: helm-chart-builder
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
